### ISSUE TITLE
Credit or Acknowledgement to Original Code Repository

### ISSUE THREAD

**Issue by jamestiotio** [RamachandraKulkarni/AudioForgeryDetection#1]
Hi there!

I am James, one of the team members who developed [this project](https://github.com/MarkHershey/AudioDeepFakeDetection). After looking through your code repository, I believe that your codebase is very similar to our project's codebase. Furthermore, it seems that you are using our code as part of your university project's submission.

While we are honoured that our project is getting recognized by more people, and while we do release our codebase as open-source, we would appreciate it if you could kindly provide some form of credit, acknowledgement, or citation to our original code repository. This is especially so since your project seems to be of an academic nature under Professor Prabhu R. Bevinamarad.

Additionally, it also seems that you did not seem to perform any significant changes to the core scripts of our codebase. Cross-referencing your university's Code of Conduct [here](http://bldeacet.ac.in/PDF/SCOC.pdf), it seems that plagiarism is not acceptable and proper attribution is required for research and academic work, as per usual. Thus, we would appreciate it if you acknowledge this codebase as our work instead of yours for your project's submission.

Alternatively, you could also fork our original codebase and perform further changes under your repository. We would still appreciate some form of citation if you officially submit this code as part of your university project's submission.

Thank you!

**Comment by RamachandraKulkarni** [comment]
Hi there!
I do understand the efforts that you guys have made for the development of
this project. Since we are submitting the survey implementation, the
referencing to the parent directory
https://github.com/MarkHershey/AudioDeepFakeDetection has been given while
submitting the project.
So, it's my gratitude to you people for letting us people use your codebase
to understand the concept.
Furthermore to let you know that while submitting the hard copy reports of
the survey, referencing to the above mentioned parent directory has been
made.

Thank you!

**Comment by RamachandraKulkarni** [comment]
Hi there!
I do understand the efforts that you guys have made for the development of this project. Since we are submitting the survey implementation, the referencing to the parent directory https://github.com/MarkHershey/AudioDeepFakeDetection has been given while submitting the project.
So, it's my gratitude to you people for letting us people use your codebase to understand the concept.
Furthermore to let you know that while submitting the hard copy reports of the survey, referencing to the above mentioned parent directory has been made.

Any further doubts please contact me directly @ramachandrask01@gmail.com

Thank you!

**Comment by jamestiotio** [comment]
Ah, alright then, that sounds great. Thank you for informing us and all the best for your project!
